### ISSUE TITLE
More > Transactions > Transaction information

### ISSUE THREAD

**Issue by rodolfomartinez** [comiccoin-network/monorepo#5]
**Summary:**
When receiving free 10 coins from the faucet, the following fields are blank:

Data
Nonce
Gas Price
Gas Unit
R
S
V
Tip

Are these fields supposed to be blank? If so, should we use N/A or something similar?

**Comment by bartmika** [comment]
> Are these fields supposed to be blank?
@rodolfomartinez Yup they are! I replaced them with a standard flat transaction fee and forgot to update the GUI in the wallet to remove those. Will do that now! Thanks.

**Comment by rodolfomartinez** [comment]
fixed
