### ISSUE TITLE
Wallet data when upgrading

### ISSUE THREAD

**Issue by rodolfomartinez** [comiccoin-network/monorepo#7]
**Summary:**
I deleted and installed a new version of the wallet. Initially, I was asked to setup a new wallet. I canceled the setup, and when I reopened the app, it had all previous data and did not show the setup screen again. It also did not ask for my password; it simply opened into the wallet.

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by rodolfomartinez** [comment]
fixed
